# ------------
# | Wrappers |
# ------------
[tasks.fmt]
command = "cargo"
args = ["fmt"]
private = true

[tasks.check]
command = "cargo"
args = ["check"]
private = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]
private = true

# -------------
# | Executors |
# -------------
[tasks.checkf]
dependencies = ["fmt", "check"]

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]

[tasks.genkey]
command = "openssl"
args = [
  "req",
  "-new",
  "-subj",
  "/CN=fuwn.me",
  "-x509",
  "-newkey",
  "ec",
  "-pkeyopt",
  "ec_paramgen_curve:prime256v1",
  "-days",
  "365",
  "-nodes",
  "-out",
  ".locus/locus_public.pem",
  "-keyout",
  ".locus/locus_private.pem",
  "-inform",
  "pem",
]

[tasks.run]
dependencies = ["checkfc"]
command = "cargo"
args = ["run", "--", "{@}"]

[tasks.docker-build]
dependencies = ["checkfc"]
command = "docker"
args = ["build", "-t", "fuwn/locus", "."]
