# ------------
# | Wrappers |
# ------------
[tasks.fmt]
command = "cargo"
args = ["fmt"]
private = true

[tasks.check]
command = "cargo"
args = ["check"]
private = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]
private = true

# -------------
# | Executors |
# -------------
[tasks.checkf]
dependencies = ["fmt", "check"]

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]

# openssl req -x509 -newkey rsa:4096 -keyout windmark_private.pem -out windmark_public.pem -days 365

[tasks.genkey]
command = "openssl"
args = [
  "req",
  "-newkey",
  "rsa:2048",
  "-new",
  "-nodes",
  "-keyout",
  "windmark_private.pem",
  "-out",
  "windmark_public.pem",
  "-subj",
  "/CN=fuwn.me"
]

[tasks.fixkey]
command = "openssl"
args = [
  "x509",
  "-req",
  "-days",
  "365",
  "-in",
  "windmark_public.pem",
  "-signkey",
  "windmark_private.pem",
  "-out",
  "windmark_pair.pem"
]

[tasks.run]
dependencies = ["checkfc"]
command = "cargo"
args = ["run", "--", "{@}"]

[tasks.docker-build]
dependencies = ["checkfc"]
command = "docker"
args = ["build", "-t", "fuwn/locus", "."]
